version: "3"

services:
  influxdb:
    image: influxdb:2.1.1
    volumes:
      - /portainer/Files/AppData/Config/influxdb2:/var/lib/influxdb2:rw
    env_file:
      - stack.env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  telegraf:
    image: telegraf:1.19
    volumes:
      - /portainer/Files/AppData/Config/telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf:rw
    env_file:
      - stack.env
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana-oss:8.4.3
    volumes:
      - /portainer/Files/AppData/Config/grafana/grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000

volumes:
  grafana-storage:
  influxdb-storage:
